CREATE TABLE "cities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"province_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "dealerships" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(200) NOT NULL,
	"slug" varchar(250) NOT NULL,
	"website_url" text,
	"base_url" text,
	"used_vehicles_url" text,
	"phone" varchar(50),
	"email" varchar(200),
	"whatsapp" varchar(50),
	"city_id" integer,
	"province_id" integer,
	"address" text,
	"coordinates" jsonb,
	"official_brand" varchar(100),
	"dealership_type" varchar(50) DEFAULT 'multimarca',
	"business_hours" jsonb,
	"exploration_enabled" boolean DEFAULT true,
	"exploration_config" jsonb,
	"exploration_frequency" varchar(20) DEFAULT 'daily',
	"social_media" jsonb,
	"rating" numeric(3, 2),
	"review_count" integer DEFAULT 0,
	"is_active" boolean DEFAULT true,
	"is_verified" boolean DEFAULT false,
	"last_explored_at" timestamp,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "dealerships_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "provinces" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "provinces_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"code" varchar(10) NOT NULL,
	"country" varchar(100) DEFAULT 'Argentina' NOT NULL,
	"region" varchar(100),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "provinces_name_unique" UNIQUE("name"),
	CONSTRAINT "provinces_code_unique" UNIQUE("code")
);
--> statement-breakpoint
CREATE TABLE "vehicle_images" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"vehicle_id" uuid NOT NULL,
	"original_url" text,
	"source_filename" varchar(300),
	"gcs_url" text NOT NULL,
	"gcs_bucket" varchar(100) DEFAULT 'garage-ai-images' NOT NULL,
	"gcs_path" text NOT NULL,
	"gcs_filename" varchar(300) NOT NULL,
	"image_order" integer DEFAULT 0,
	"image_type" varchar(50) DEFAULT 'exterior',
	"is_primary" boolean DEFAULT false,
	"file_size" integer,
	"mime_type" varchar(100),
	"width" integer,
	"height" integer,
	"upload_status" varchar(20) DEFAULT 'pending',
	"processed_at" timestamp,
	"tags" jsonb,
	"ai_analysis" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "vehicles" ALTER COLUMN "currency" SET DEFAULT 'ARS';--> statement-breakpoint
ALTER TABLE "vehicles" ALTER COLUMN "location_country" SET DEFAULT 'Argentina';--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "dealership_id" uuid;--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "city_id" integer;--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "province_id" integer;--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "seller_type" varchar(50) DEFAULT 'dealership';--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "opportunity_score" integer;--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "quality_score" integer;--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "market_price" numeric(12, 2);--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "price_variation" numeric(5, 2);--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "status" varchar(20) DEFAULT 'available';--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "featured" boolean DEFAULT false;--> statement-breakpoint
ALTER TABLE "vehicles" ADD COLUMN "verified_at" timestamp;--> statement-breakpoint
ALTER TABLE "cities" ADD CONSTRAINT "cities_province_id_provinces_id_fk" FOREIGN KEY ("province_id") REFERENCES "public"."provinces"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dealerships" ADD CONSTRAINT "dealerships_city_id_cities_id_fk" FOREIGN KEY ("city_id") REFERENCES "public"."cities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "dealerships" ADD CONSTRAINT "dealerships_province_id_provinces_id_fk" FOREIGN KEY ("province_id") REFERENCES "public"."provinces"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicle_images" ADD CONSTRAINT "vehicle_images_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "public"."vehicles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "cities_province_city_idx" ON "cities" USING btree ("province_id","name");--> statement-breakpoint
CREATE INDEX "dealerships_name_idx" ON "dealerships" USING btree ("name");--> statement-breakpoint
CREATE INDEX "dealerships_city_idx" ON "dealerships" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "dealerships_province_idx" ON "dealerships" USING btree ("province_id");--> statement-breakpoint
CREATE INDEX "dealerships_brand_idx" ON "dealerships" USING btree ("official_brand");--> statement-breakpoint
CREATE INDEX "dealerships_active_idx" ON "dealerships" USING btree ("is_active");--> statement-breakpoint
CREATE INDEX "dealerships_exploration_idx" ON "dealerships" USING btree ("exploration_enabled","exploration_frequency");--> statement-breakpoint
CREATE INDEX "vehicle_images_vehicle_idx" ON "vehicle_images" USING btree ("vehicle_id");--> statement-breakpoint
CREATE INDEX "vehicle_images_primary_idx" ON "vehicle_images" USING btree ("is_primary");--> statement-breakpoint
CREATE INDEX "vehicle_images_type_idx" ON "vehicle_images" USING btree ("image_type");--> statement-breakpoint
CREATE INDEX "vehicle_images_status_idx" ON "vehicle_images" USING btree ("upload_status");--> statement-breakpoint
CREATE INDEX "vehicle_images_gcs_path_idx" ON "vehicle_images" USING btree ("gcs_path");--> statement-breakpoint
ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_dealership_id_dealerships_id_fk" FOREIGN KEY ("dealership_id") REFERENCES "public"."dealerships"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_city_id_cities_id_fk" FOREIGN KEY ("city_id") REFERENCES "public"."cities"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_province_id_provinces_id_fk" FOREIGN KEY ("province_id") REFERENCES "public"."provinces"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "vehicles_dealership_idx" ON "vehicles" USING btree ("dealership_id");--> statement-breakpoint
CREATE INDEX "vehicles_city_idx" ON "vehicles" USING btree ("city_id");--> statement-breakpoint
CREATE INDEX "vehicles_province_idx" ON "vehicles" USING btree ("province_id");--> statement-breakpoint
CREATE INDEX "vehicles_opportunity_idx" ON "vehicles" USING btree ("is_opportunity_ai","opportunity_score");--> statement-breakpoint
CREATE INDEX "vehicles_status_idx" ON "vehicles" USING btree ("status");