-- Migration: Create dealerships schema with provinces, cities, and vehicle relationships
-- Date: 2025-08-05

-- Create provinces table
CREATE TABLE IF NOT EXISTS "provinces" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "provinces_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"code" varchar(10) NOT NULL,
	"country" varchar(100) DEFAULT 'Argentina' NOT NULL,
	"region" varchar(100),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "provinces_name_unique" UNIQUE("name"),
	CONSTRAINT "provinces_code_unique" UNIQUE("code")
);

-- Create cities table
CREATE TABLE IF NOT EXISTS "cities" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cities_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"province_id" integer NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

-- Create dealerships table  
CREATE TABLE IF NOT EXISTS "dealerships" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"name" varchar(200) NOT NULL,
	"slug" varchar(250) NOT NULL,
	"website_url" text,
	"base_url" text,
	"used_vehicles_url" text,
	"phone" varchar(50),
	"email" varchar(200),
	"whatsapp" varchar(50),
	"city_id" integer,
	"province_id" integer,
	"address" text,
	"coordinates" jsonb,
	"official_brand" varchar(100),
	"dealership_type" varchar(50) DEFAULT 'multimarca',
	"business_hours" jsonb,
	"exploration_enabled" boolean DEFAULT true,
	"exploration_config" jsonb,
	"exploration_frequency" varchar(20) DEFAULT 'daily',
	"social_media" jsonb,
	"rating" numeric(3,2),
	"review_count" integer DEFAULT 0,
	"is_active" boolean DEFAULT true,
	"is_verified" boolean DEFAULT false,
	"last_explored_at" timestamp,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "dealerships_slug_unique" UNIQUE("slug")
);

-- Create vehicle_images table for Google Cloud Storage
CREATE TABLE IF NOT EXISTS "vehicle_images" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid(),
	"vehicle_id" uuid NOT NULL,
	"original_url" text,
	"source_filename" varchar(300),
	"gcs_url" text NOT NULL,
	"gcs_bucket" varchar(100) DEFAULT 'garage-ai-images' NOT NULL,
	"gcs_path" text NOT NULL,
	"gcs_filename" varchar(300) NOT NULL,
	"image_order" integer DEFAULT 0,
	"image_type" varchar(50) DEFAULT 'exterior',
	"is_primary" boolean DEFAULT false,
	"file_size" integer,
	"mime_type" varchar(100),
	"width" integer,
	"height" integer,
	"upload_status" varchar(20) DEFAULT 'pending',
	"processed_at" timestamp,
	"tags" jsonb,
	"ai_analysis" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);

-- Add foreign key constraints
DO $$ BEGIN
 ALTER TABLE "cities" ADD CONSTRAINT "cities_province_id_provinces_id_fk" FOREIGN KEY ("province_id") REFERENCES "provinces"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "dealerships" ADD CONSTRAINT "dealerships_city_id_cities_id_fk" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "dealerships" ADD CONSTRAINT "dealerships_province_id_provinces_id_fk" FOREIGN KEY ("province_id") REFERENCES "provinces"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "vehicle_images" ADD CONSTRAINT "vehicle_images_vehicle_id_vehicles_id_fk" FOREIGN KEY ("vehicle_id") REFERENCES "vehicles"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

-- Add dealership_id column to vehicles table if it doesn't exist
DO $$ BEGIN
 ALTER TABLE "vehicles" ADD COLUMN "dealership_id" uuid;
EXCEPTION
 WHEN duplicate_column THEN null;
END $$;

-- Add city_id and province_id columns to vehicles table if they don't exist  
DO $$ BEGIN
 ALTER TABLE "vehicles" ADD COLUMN "city_id" integer;
EXCEPTION
 WHEN duplicate_column THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "vehicles" ADD COLUMN "province_id" integer;
EXCEPTION
 WHEN duplicate_column THEN null;
END $$;

-- Add foreign key constraints for vehicles table
DO $$ BEGIN
 ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_dealership_id_dealerships_id_fk" FOREIGN KEY ("dealership_id") REFERENCES "dealerships"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_city_id_cities_id_fk" FOREIGN KEY ("city_id") REFERENCES "cities"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
 ALTER TABLE "vehicles" ADD CONSTRAINT "vehicles_province_id_provinces_id_fk" FOREIGN KEY ("province_id") REFERENCES "provinces"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS "cities_province_city_idx" ON "cities" ("province_id","name");
CREATE INDEX IF NOT EXISTS "dealerships_name_idx" ON "dealerships" ("name");
CREATE INDEX IF NOT EXISTS "dealerships_city_idx" ON "dealerships" ("city_id"); 
CREATE INDEX IF NOT EXISTS "dealerships_province_idx" ON "dealerships" ("province_id");
CREATE INDEX IF NOT EXISTS "dealerships_brand_idx" ON "dealerships" ("official_brand");
CREATE INDEX IF NOT EXISTS "dealerships_active_idx" ON "dealerships" ("is_active");
CREATE INDEX IF NOT EXISTS "dealerships_exploration_idx" ON "dealerships" ("exploration_enabled","exploration_frequency");
CREATE INDEX IF NOT EXISTS "vehicle_images_vehicle_idx" ON "vehicle_images" ("vehicle_id");
CREATE INDEX IF NOT EXISTS "vehicle_images_primary_idx" ON "vehicle_images" ("is_primary");
CREATE INDEX IF NOT EXISTS "vehicle_images_type_idx" ON "vehicle_images" ("image_type");
CREATE INDEX IF NOT EXISTS "vehicle_images_status_idx" ON "vehicle_images" ("upload_status");
CREATE INDEX IF NOT EXISTS "vehicle_images_gcs_path_idx" ON "vehicle_images" ("gcs_path");
CREATE INDEX IF NOT EXISTS "vehicles_dealership_idx" ON "vehicles" ("dealership_id");
CREATE INDEX IF NOT EXISTS "vehicles_city_idx" ON "vehicles" ("city_id");
CREATE INDEX IF NOT EXISTS "vehicles_province_idx" ON "vehicles" ("province_id");